#!/bin/bash

WLAN=$(ifconfig -a | cut -c1-8 | grep wl)
iw dev $WLAN interface add ap0 type __ap
ip link set down dev ap0
ip addr flush ap0
ip link set up dev ap0
ip addr add 192.168.12.1/24 broadcast 192.168.12.255 dev ap0